apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
      - name: xxx
        image: xxx
        ports:
        - containerPort: xxx
        env:
        - name: PORT
          value: "xxx"
---
apiVersion: v1
kind: xxx
metadata:
    name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080 